spring:
  datasource:
    #url: jdbc:mysql://192.168.73.23:3306/kasprobank?useSSL=false
    url: jdbc:mysql://localhost:3307/kasprobank?useSSL=false
    #Prod
    #url: jdbc:mysql://dabdb-pub.mysql.ap-southeast-5.rds.aliyuncs.com:6033/kasprobank?useSSL=false
    #prod
    #username: bankadm
    #password: B@nk-PRO1
    username: devuser
    password: Kokas2020!#
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTestQuery: SELECT 1
      connectionTimeout: 6000
      idleTimeout: 0
      maxLifetime: 1800000
      maximumPoolSize: 10
      minimumIdle : 5
  messages:
    basename: messages/messages
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8888