spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ms-payment?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTestQuery: SELECT 1
      connectionTimeout: 6000
      idleTimeout: 20000
      maxLifetime: 30000
      maximumPoolSize: 5
      minimumIdle : 3
  messages:
    basename: messages/messages
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8888